<?php
/**
 * Created by PhpStorm.
 * User: FS05
 * Date: 15/12/17
 * Time: 12:54
 */

namespace frontend\widgets;


use yii\base\Widget;

class PlayerWidget extends Widget
{
    public $player;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {


        return $this->render('player', ['player' => $this->player]);
    }
}