<?php
/**
 * Created by PhpStorm.
 * User: FS05
 * Date: 14/12/17
 * Time: 12:01
 */

namespace frontend\widgets;


use yii\base\Widget;

class TeamWidget extends Widget
{
    public $team_data, $team_players, $closest_challenge, $few_matches_data, $last_match_data;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('team', ['team_data' => $this->team_data, 'team_players' => $this->team_players, 'closest_challenge' => $this->closest_challenge, 'few_matches_data' => $this->few_matches_data, 'last_match_data' => $this->last_match_data]);
    }
}